### ISSUE TITLE
Upgrade h5p-php-library (Wrong color for h5p-actions in footer)

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#1142]
**Incorrect color code**
The footer buttons for reuse, embed, rights of use within h5p-actions should use color code: #707070 and not #999 

Inspect https://ndla.no/subject:1:6f770e8e-7426-4b43-b1b1-9c12bbbcae43/topic:2:189367/topic:2:189466/resource:1:143421
vs.
https://h5p.org/presentation

**Comment by tmkarlsen** [comment]
Note: there is also a typing error within the Norwegian translation for "Use this content"/"Bruk dette innholdet" on mouse over for download.

**Comment by chrieinv** [comment]
A new version of the Composer package `h5p/h5p-core` with the changed color is not yet available. Current version is 1.24.3.

**Comment by tmkarlsen** [comment]
Ticket opened with question for when text release is due: https://github.com/h5p/h5p-php-library/issues/125

**Comment by tmkarlsen** [comment]
Impossible to know when  **next** release is due. Would a workaround be possible/appropriate?

**Comment by Kamelon7** [comment]
Seems like it might be fixed now: https://github.com/h5p/h5p-php-library/commit/ce327e08debdeab94d4cf0fd313bbc1499b41029

**Comment by chrieinv** [comment]
Still no new version, latest tagged is 1.24.3: https://packagist.org/packages/h5p/h5p-core

**Comment by tmkarlsen** [comment]
New version released:

https://github.com/h5p/h5p-php-library/releases/tag/1.24.4

**Comment by emmachughes** [comment]
The new version makes no changes that are relevant to this issue.

https://github.com/h5p/h5p-php-library/compare/1.24.3...1.24.4

**Comment by tmkarlsen** [comment]
My bad. Forgot to check the actual changes, just assumed. Should have understood that the changes were minor though...
