### ISSUE TITLE
SQL Error code when trying to save

### ISSUE THREAD

**Issue by finnpose** [cerpus/Edlib#1163]
In Edlib content creator.
Selected to create a question.
I managed to recreate the error and took screenshots.

Bug(s) occur in test and prod.

**Error**
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'is_draft' cannot be null (SQL: insert into `question_sets` (`title`, `owner`, `language_code`, `is_published`, `license`, `is_draft`, `id`, `updated_at`, `created_at`) values (Hvor ligger Enebakk Kommune?, 190ee740-26cb-4a19-8a8c-fe666b0c4999, en, 0, BY, ?, a05cce58-7473-4ed2-8edb-a1ca2df51e87, 2022-05-19 12:18:33, 2022-05-19 12:18:33))

**How to recreate the error**
1. Create content - Choose "Question"
2. Fill in title, one question and 4 answers and hit "generate quiz"

**Expected behavior**
I expected to save a quiz question.

**Screenshots**

![Skjermbilde 2022-05-19 kl  14 18 08](https://user-images.githubusercontent.com/105861259/169291832-8fb3cf09-8562-4607-a669-3d5ec5078023.png)

![Skjermbilde 2022-05-19 kl  14 18 28](https://user-images.githubusercontent.com/105861259/169291884-049cf997-a94b-4613-8e15-d9c2f639d954.png)

![Skjermbilde 2022-05-19 kl  14 18 46](https://user-images.githubusercontent.com/105861259/169291953-5220d6bb-952d-4932-a54b-880884e7aa3e.png)

**Desktop (please complete the following information):**

- OS: MacOS 12.3.1
- Browser: Firefox
- Version: 100.0.1 (64-bit)

**Comment by tmkarlsen** [comment]
1. I get 500 on Request URL: https://ca.test.edlib.cerpusdev.net/v1/questionsets?title= as soon as I leave the title field with content
2. I get 404 on the missing SVG when clicking "Quiz" as presentation form: Request URL: https://ca.test.edlib.cerpusdev.net/h5pstorage/libraries/H5P.QuestionSet-1.13/icon.svg
3. I get 500 on Request URL: https://ca.test.edlib.cerpusdev.net/questionset when hitting "Generate Quiz"

**Screenshots**
![Skjermbilde 2022-05-19 kl  15 33 23](https://user-images.githubusercontent.com/38659798/169308346-af006159-650e-448d-8ac6-d4b4e5abd9ec.png)

![Skjermbilde 2022-05-19 kl  15 46 27](https://user-images.githubusercontent.com/38659798/169308619-ab3bb562-3ef5-49f5-baa8-b117ccd0ff02.png)
