### ISSUE TITLE
Missing resources should result in 404

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#124]
**Missing resources in Edlib should respond correctly**
This article is missing a resource but does not respond with a 404, which makes it hard to detect. This should be solved both internally and externally in order to give the provider a better overview
https://ndla.no/nn/subject:1:01c27030-e8f8-4a7c-a5b3-489fdb8fea30/topic:2:182849/topic:2:163658/resource:1:163513
![Skjermbilde 2021-11-15 kl  15 03 47](https://user-images.githubusercontent.com/38659798/141795447-d0a86d49-c793-4e95-ad59-61ddd4e5a7e5.png)

**Comment by maxmoeschinger** [comment]
Edlib is already returning 404
