### ISSUE TITLE
H5P resizer.js should load from Edlib, not H5P.org

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#1244]
This javascript should be copied and run from Edlib

**Screenshot**
<img width="1242" alt="Skjermbilde 2022-08-01 kl  10 00 27" src="https://user-images.githubusercontent.com/38659798/182101711-2a829d79-e814-4340-b85d-89b7d1ececd9.png">

Example resource: https://ndla.no/nn/subject:1:6f770e8e-7426-4b43-b1b1-9c12bbbcae43/topic:2:189367/topic:2:189466/resource:1:143421

**Comment by tmkarlsen** [comment]
@emmachughes isn't this issue merged to master? I think so.

**Comment by emmachughes** [comment]
This is an edlibfacade issue, and yes, it is merged.
