### ISSUE TITLE
Wrong version of file used in Edlib

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#1250]
**JS-file not updated**

https://github.com/NDLANO/h5p-three-image is updated to a new version 0.4.89 and uploaded to Edlib, but the three-image.js file used is not the one within the .h5p file it seems.

The newest version of this file contains void 0!==this.props.imageSrc 

Potential fix to NDLA Interactive Board error as well.

**Comment by emmachughes** [comment]
The problem was solved by having CloudFront take the `?ver=x.y.z` query string into consideration when caching the library files.
