### ISSUE TITLE
Brightcove video integration

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#1476]

**Comment by emmachughes** [comment]
In NDLA mode, a [.js script](https://github.com/cerpus/Edlib/blob/288094972378ab75eacf48037ade6fba34772780/sourcecode/apis/contentauthor/public/js/videos/brightcove.js) that registers an H5P video handler is added to the frontend assets. This handler is then [used by the H5P.Video library](https://github.com/h5p/h5p-video/blob/df9a20848cf37e3d5a85d4915f61c8caedb1bfc5/scripts/video.js) to play Brightcove videos, which have "fake" `https://bc/` URLs. The ID is extracted from the URL and passed to the Brightcove loader.
