### ISSUE TITLE
H5P - Play button in progression bar does not respond

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#1529]
**Play button does not respond**
The play button down in progression bar does not respond in Interactive video. This works on H5P.org.

**To Reproduce**
Go to https://www.h5p.ndla.no/s/resources/a4915ef6-9762-43fa-b8c0-0cb1f8cf12c3

**Comment by tmkarlsen** [comment]
Estimate: 5,3 hours (PERT)

**Comment by chrieinv** [comment]
Tested OK on Windows 10 on browsers
- Firefox 110.0.1
- Chrome 110.0.5481.178
- Vivaldi 5.6.2867.62

@tmkarlsen Can you retest?

**Comment by tmkarlsen** [comment]
Tested OK on MacOs Ventura 13.2.1

- Chrome 110.0.5481.177
- Firefox 110.0.1
- Vivaldi 5.7.2921.60
- Safari 16.3
