### ISSUE TITLE
User is missing resources

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#1552]
**Missing resources in "My content**
Look into if all resources are displayed (correctly) within "My content"

Note: environment is ndla-test

**Comment by emmachughes** [comment]
@tmkarlsen Can you provide one resource that shows up correctly, and one that doesn't?

**Comment by tmkarlsen** [comment]
Resource that is missing and created by the user:
https://www.h5p-test.ndla.no/s/resources/d4a9b1c0-303f-48c2-9998-e38a68262e8c
https://www.h5p-test.ndla.no/s/resources/4f5cccd2-81f5-4027-88f3-528ab037116f
https://www.h5p-test.ndla.no/s/resources/56934cda-787f-479a-9474-f7d3833247ac

Resources shown in "My resources" and created by the user:
https://www.h5p-test.ndla.no/s/resources/fd6f70df-98ba-44b5-ab98-e78a9d1142b0

**Comment by emmachughes** [comment]
For whatever reason, the missing resources and the one not missing belong to two different user IDs. Both users have the same email and are marked admin.

The fault is possibly with the authentication method NDLA uses—our database uses an entirely different format for the user IDs—so I suspect it's an external system that delegates the IDs. For some reason, this has resulted in two different IDs being delegated to the same user.

**Comment by emmachughes** [comment]
@tmkarlsen What's the status on this?

**Comment by tmkarlsen** [comment]
This was not problematized by the user later on, so it is probably only a test environment issue. 
Closing it for now.
