### ISSUE TITLE
Exclude own organizational users from Matomo

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#1554]
We need to get a real picture of how many visits docs.edlib.com.
It is therefore important that we sort out and exclude the following traffic:

- [x] Internal users
- [x] Traffic on test environment

**Comment by Kamelon7** [comment]
The test environment has been excluded now. The settings needed to do this mean that any new subdomains must be added to Matomo settings (e.g., new.edlib.com).
The IP address of the Alsvåg office has been excluded. The same needs to be done with the Bodø office when ready.

**Comment by Kamelon7** [comment]
The K&S offices has also been excluded. Will mark this issue as solved.
