### ISSUE TITLE
H5P resource breaks during update

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#1647]
**Trying to update a resource**
https://www.h5p.ndla.no/s/resources/22626f3c-ad5c-4fa5-85d3-0edfee55b813 

Id | 174230
Sist endret | 14. aug. 2022 kl. 09:57
Type | Question Set 1.17
Maks poeng | 21

1. When loading the resource for editing the following error message displays:
Uncaught SyntaxError: Cannot use import statement outside a module (at question-set-textual-editor.js?ver=1.3.15:1:1)

2. When updating the H5P library (not saving) the following error messages displays:

- Uncaught SyntaxError: Cannot use import statement outside a module (at question-set-textual-editor.js?ver=1.3.15:1:1)
- Uncaught TypeError: Cannot read properties of undefined (reading 'versions') h5peditor-file.js?ver=2.0.2:197  

**Screenshots**

![Image](https://user-images.githubusercontent.com/38659798/191200895-4bcca60d-8b40-44de-ac31-8b0f3800fdc2.png)

![Skjermbilde 2022-09-07 kl  13 06 51](https://user-images.githubusercontent.com/38659798/189320073-0886fbbf-b6df-4c62-a05d-e8f8671c3ec9.png)

![Skjermbilde 2022-09-09 kl  12 12 01](https://user-images.githubusercontent.com/38659798/189327815-466b2201-a529-4674-91db-b27f1416f549.png)

![Skjermbilde 2022-09-09 kl  12 13 12](https://user-images.githubusercontent.com/38659798/189327828-65774bca-637c-4e1a-aa04-ec9d882bc3de.png)

**Comment by chrieinv** [comment]
@tmkarlsen You are updating a Question Set resource from version 1.17? What version are you updating to?

**Comment by chrieinv** [comment]
Downloaded the resource and uploaded it to my local dev environment. Updated to version 1.20.7, without any errors. Also updated a different Question Set resource I had that was on version 1.12.2 without any errors.

**Comment by tmkarlsen** [comment]
@chrieinv Yes, that is correct. Updated from 1.17 to 1.20.5

**Comment by tmkarlsen** [comment]
Could this be some of the same issues we are seeing context of the image/editor-bug? https://github.com/cerpus/Edlib/issues/1642

**Comment by chrieinv** [comment]
Both these seems to be missing images, the placeholder image is displayed. This may be because it was edited when the #1642 bug was present, causing the semantics to be incorrect. Try to edit the resource, add the missing image(s), and retry the update.

**Comment by tmkarlsen** [comment]
It seems like the library has not been compiled from source, as there are differences in the code between the database and the source code.

**Comment by chrieinv** [comment]
This can be resolved by uploading a newer patch version of the library

**Comment by tmkarlsen** [comment]
The resource https://www.h5p.ndla.no/s/resources/22626f3c-ad5c-4fa5-85d3-0edfee55b813 is updated.
