### ISSUE TITLE
Find videos for migrating

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#1684]
Deal with videos on-premise

1. Locate all videos stored on-prem via Edlib
2. Look into solution for them. Possibly migrating then to an S3 bucket.

**Comment by emmachughes** [comment]
From what I can tell, videos uploaded prior to the AWS migration were moved to S3 near the end of 2021. Closing as I don't think there's anything to do here.

**Comment by tmkarlsen** [comment]
We have also verified that videos added to content today are stored in S3.
