### ISSUE TITLE
Remove streamps-integration

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#1751]
The old Streamps video integration is no longer used and should be removed from Edlib.

**Comment by tmkarlsen** [comment]
Is it not risky to run this without any transcoding? Most users never give a second thought to the video files they upload and just expect them to work.

If needed, what transcoding options do we have?

- https://aws.amazon.com/elastictranscoder/

**Comment by emmachughes** [comment]
It's not risky per se, but it could lead to uploaded videos not playing back in the browser. I'm not fond of this solution, but given the current time constraints, it might be what we have to go for.

We can always add transcoding later.

**Comment by tmkarlsen** [comment]
Agree. I've added this issue for later: https://github.com/cerpus/Edlib/issues/1755

**Comment by tmkarlsen** [comment]
An other solution is disabling the upload for now.
Could you check how many uploaded videos we have in 2022 @emmachughes ?

**Comment by emmachughes** [comment]
There are 187 videos uploaded in 2022.

**Comment by tmkarlsen** [comment]
The streamps server is now no longer in contact with Edlib, so we'll close this issue and follow up on the transcoding part in #1755
