### ISSUE TITLE
Translation missing + minor adjustment

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#1819]
**"From" and "To" needs to be translatable**
- Make sure the "From" and "To" is translatable to other languages.
- Add Norwegian translation: "Fra" "Til"

- Remove space before colon on "Range view" and "Total views"

**Screenshot**
![Skjermbilde 2022-11-09 kl  12 17 41](https://user-images.githubusercontent.com/38659798/200816560-1e371895-53c8-44b8-9f21-5802a7ed46bf.png)

**Comment by ssethupathy** [comment]
This issue fixed
