### ISSUE TITLE
Simplify buttons and dialogs 

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#1841]
**1.  Dialogs to insert content** 

Note: Today we have two different buttons for two different contexts that does this: 

*Changes to be done:*
- [ ] 1. "USE RESOURCE" from preview in CE shall be changed to "Use content" / "Bruk innhold"
- [ ] 2. "SAVE AND CLOSE" shall be changed to "Save and close" / "Lagre og lukk" from editing in CA
- [ ] 3. "Insert" (from the mini menu) in CE shall be changed to "Use content" / "Bruk innhold".

**2. Dialogs to edit content**  

Note: as of today, there are two different scenarios, and that we might need to make difference between the two texts: 
1.  editing your own content from "My content". 
2. editing content someone else has created and shared - meaning that you make a copy of it and edit this copy. Look at previous suggestions from earlier rounds of redesign "Copy and edit" (Note: remember NDLA has a different setup)

*Changes to be done:*
- [ ] 1. "EDIT RESOURCE" shall be changed to "Edit content" / "Rediger innhold"

**3. Header entries**

*Changes to be done:*
- [ ] 1. "CREATE CONTENT" shall be changed to "Create content" / "Opprett innhold"
- [ ] 2. "SHARED CONTENT" shall be changed to "Find shared content" / "Finn delt innhold"
- [ ] 3. "MY CONTENT" shall be changed to "My content" / "Mitt innhold"

Note: no changes to the icons at this point.

**4. Questions entries**
*Changes to be done:*
- [ ] 1. "ANSWER" shall be changed to "Add option" / "Legg til svaralternativ"
- [ ] 2. "ADD QUESTION" shall be changed to "Add question" / "Legg til spørsmål"
- [ ] 3. "MILLIONAIRE" shall be changed to "Millionaire mini game" / "Millionær-minispill"
- [ ] 4. "QUIZ" shall be changed to "Question Set (H5P)" / "Question Set (H5P)"
- [ ] 5. "Chose presentation form" shall be set as an H2

**5. Filter section**
*Changes to be done:*
- [ ] 1. "RESET" shall be changed to "Reset" / "Nullstill"
- [ ] 2. "Game" shall be changed to "Millionaire mini game" / "Millionær minispill"
- [ ] 3. "GROUPED" shall be changed to "Grouped" / "Gruppert"
- [ ] 4. "SAVE FILTER" shall be changed to "Save filter" / "Lagre filter"
- [ ] 5. "CANCEL" shall be changed to "Cancel" / "Avbryt" (Edit filter dialog) 
- [ ] 6. "SAVE" shall be changed to "Save" / "Lagre" (Edit filter dialog)
- [ ] 7. "DELETE" shall be changed to "Delete" / "Slett" (Edit filter dialog)

**Comment by finnpose** [comment]
New naming convention proposal:

Top bar:

Create content
My content
Shared content

Buttons in both preview mode and edit mode:

Change from

“Edit resource” to “Edit content” or simply “edit”
“Use resource” to “copy content” or simply “copy”

Publish and unpublish buttons in preview mode.

Remove exit button. The X in top right corner is enough.

Try to get all buttons in the control panel for consistency

Structure on control panel Save ➡ Publish ➡ Use
When returned to Gamilab change “Save” to “Use content”

We must discuss if we want edlib or gamilab to have the use content.

I am not sure about using insert. It is a bit confusing.

Resource change to content. for example this alert that comes up in Gamilab if it is a draft:

This resource is in a draft state which means that it won’t display on the internet. To use it, you have to edit it and then set to “published”

-change to-

This content is in draft state which means that it will not display on the internet. To use it, you have to publish it.
