### ISSUE TITLE
Adjust padding for embedded H5Ps

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#1846]
**Superflous padding on H5P embed from Edlib**

Current embeds have 24 px padding on both sides for H5Ps, which is not wanted. 
H5Ps should utilize the whole width and adjust the height accordingly. 

WP test site
https://nettstudiene.no/tmk-test-2

**Screenshots**

![Skjermbilde 2022-11-28 kl  11 05 31](https://user-images.githubusercontent.com/38659798/204271416-6cdfa613-90f9-41bd-8509-29d7a66c8178.png)

**Comment by emmachughes** [comment]
Which URL does this appear on? Which element has this padding?

I'm not convinced this padding is something we apply.

**Comment by tmkarlsen** [comment]
Test shows remaining 8 px of padding:

![Skjermbilde 2022-12-07 kl  13 42 35](https://user-images.githubusercontent.com/38659798/206182471-60c6f9dc-f6f9-46f2-8ccd-2da0de1efecc.png)

![Skjermbilde 2022-12-07 kl  13 43 08](https://user-images.githubusercontent.com/38659798/206182481-be6129d1-70b3-44dc-931c-77dcdafd1c1d.png)

![Skjermbilde 2022-12-07 kl  13 43 26](https://user-images.githubusercontent.com/38659798/206182499-54b6bd9b-9be0-4cef-b59e-1b6cb43b86a9.png)
