### ISSUE TITLE
Missing H5P icons.

### ISSUE THREAD

**Issue by KashifIqbal1975** [cerpus/Edlib#1961]
**Describe the bug**
The following H5P Icons are missing when you create the following content type in Edlib:

* Article
* Audio (Icon included below)
* Audio Recorder (Icon included below)
* Board Game
* Greeting card
* Find multiple hotspots (Icon included below)
* Image Juxtaposition (Icon included below)
* Personality Quiz (Icon included below)

Generic H5P Icon below can be used for all missing H5P content type.

The following non-H5P icons are missing:

* Cerpus Image 
* Cerpus Video 

Generic H5P Icon below can be used for all missing H5P content type.

**To Reproduce**
Steps to reproduce the behaviour:

1. In Edlib, go to Create content in the header.
2. Click on Create content
3. Click on Interactivity in the mini menu that appears.
4. Click on A to Z under All Content Types.
5. Select one of the content types mentioned at top.
6. Fill out and create the content.
7. Toggle the Published slider to the right.
8. Click on Save and close
9. Go back to Edlib and click under My content. You will see that your created content appears first but Icon is missing.

**Comment by KashifIqbal1975** [comment]
![audio](https://user-images.githubusercontent.com/105861259/210803994-b7c928a0-b1dc-4621-ac85-7ebd2f85d6b2.svg)
![before-after-image_0](https://user-images.githubusercontent.com/105861259/210803999-8445d50f-6d9d-46af-a263-57ae6fbd7bbb.svg)
![personality quiz](https://user-images.githubusercontent.com/105861259/210804004-352acee4-6b91-4b83-9741-c14b12550673.svg)

**Comment by chrieinv** [comment]
All of the H5P content types should provide their own icon if they want to, if they haven't the above H5P logo will be used. We are using the icon that is included in the library, the icon displayed in the H5P Hub list is set by H5P in their Hub admin system.
Cerpus Image and Cerpus Video got icons when they were renamed to Edlib Image and Edlib Video. Article is also an Edlib type and has an icon
