### ISSUE TITLE
Icons for Edlib (standardization)

### ISSUE THREAD

**Issue by ssethupathy** [cerpus/Edlib#1972]
The following icons are to be used within Edlib. 

Some icons have been changed to have better navigation. For example the published icon used previously is the same as preview icon in Gamilab. The inconsistencies need to be corrected.

![baseline_add_black_24dp](https://user-images.githubusercontent.com/113360941/212680928-bcd91651-b7da-43fd-b953-5a8b7d146442.png) - Create content
`<span class="material-icons">
add
</span>`

![baseline_check_circle_black_24dp](https://user-images.githubusercontent.com/113360941/212680931-ce79dc3a-8bf6-4ed2-bf1e-faacf5d00dc8.png) - Published
`<span class="material-icons">
check_circle
</span>`

![baseline_edit_black_24dp](https://user-images.githubusercontent.com/113360941/212680933-5abb925f-ba9f-42f4-b534-b5763d1aa4a8.png) - Edit content
`<span class="material-icons">
edit
</span>`

![baseline_launch_black_24dp](https://user-images.githubusercontent.com/113360941/212680935-2a7c27fa-5fac-42b7-93b6-506b3f1dce9c.png) - Use content
`<span class="material-icons">
launch
</span>`

![baseline_person_black_24dp](https://user-images.githubusercontent.com/113360941/212680936-2f11392d-49a0-4b63-be88-1c4e1f4bdc36.png) - My content
`<span class="material-icons">
person
</span>`

![baseline_save_black_24dp](https://user-images.githubusercontent.com/113360941/212680938-3c0610b8-698a-425e-a62f-97d5938a206e.png) - Save and close
`<span class="material-icons">
save
</span>`

![baseline_share_black_24dp](https://user-images.githubusercontent.com/113360941/212680941-6317e277-fc9d-427e-8677-98ddbdc33528.png) - Find shared content
`<span class="material-icons">
share
</span>`

![baseline_unpublished_black_24dp](https://user-images.githubusercontent.com/113360941/212680943-9dbe5dd2-35e8-48db-8b83-13ff08e0ac69.png) - Unpublished
`<span class="material-icons">
unpublished
</span>`

**Future icons for new buttons in preview and edit mode (Not assigned yet)**

![baseline_check_circle_black_24dp](https://user-images.githubusercontent.com/113360941/212680931-ce79dc3a-8bf6-4ed2-bf1e-faacf5d00dc8.png) - Publish
`<span class="material-icons">
check_circle
</span>`

![baseline_unpublished_black_24dp](https://user-images.githubusercontent.com/113360941/212680943-9dbe5dd2-35e8-48db-8b83-13ff08e0ac69.png) - Unpublish
`<span class="material-icons">
unpublished
</span>`

**Comment by tmkarlsen** [comment]
Linked internal issues: DES-428
