### ISSUE TITLE
Uncaught TypeError prohibits display of resource

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#1973]
**Error breaks display**
It seems like some older versions of H5Ps are having an "Uncaught TypeError: Cannot read properties of undefined (reading 'createButton')"
So far seen in 
- QuestionSet

Examples:
https://www.h5p.ndla.no/s/resources/f8c1b7f6-b452-4ca4-9bf0-d17bbc90e370
https://www.h5p.ndla.no/s/resources/a65c9932-7475-47d1-9078-1ec6c673d9d9
https://www.h5p.ndla.no/s/resources/c8991067-321c-4ae4-82ec-4f1fb128f226
https://www.h5p.ndla.no/s/resources/f078e42a-c1ae-4bbb-b0af-45711cad2cd4
https://www.h5p.ndla.no/s/resources/a411e4a6-257d-4dcb-aa30-a9d2727d4a04
https://www.h5p.ndla.no/s/resources/89455bdd-56a3-4d2e-86c0-0e32b7ed96eb

**Screenshots**

![Skjermbilde 2023-01-11 kl  12 33 53](https://user-images.githubusercontent.com/38659798/212886690-731809b7-2b85-4214-aae0-ef4160e343b5.png)

![Skjermbilde 2023-01-11 kl  12 33 00](https://user-images.githubusercontent.com/38659798/212886858-9243c8fd-60b0-41b4-bd9b-73884b4def83.png)

![Skjermbilde 2023-01-16 kl  13 12 59](https://user-images.githubusercontent.com/38659798/212886651-19ee18b2-12ef-4050-b7e5-64bf2c69af83.png)

**Comment by tmkarlsen** [comment]
Related to #1647 ?

**Comment by chrieinv** [comment]
The database table `h5p_contents_libraries` contains a reference to the libraries that the content uses. In this case it seems that the reference to `H5P.JoubelUI` is missing for this content. This affects the display of the content but not the edit.
Except for adding the missing reference in the database manually, clearing the `filtered` value for the content will rebuild/update the references on next view.

**Comment by tmkarlsen** [comment]
All the above mentioned content does now display correctly.

**Comment by tmkarlsen** [comment]
Cannot reproduce anymore.
