### ISSUE TITLE
Hide menu entries in Content Author admin

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#1984]
"NDLA Import" and "Games" should be hidden from the admin interface for the NDLA installation.
Check if NDLA-modus is active and hide them if it is.

**Screenshot**
![Skjermbilde 2023-01-27 kl  09 14 26](https://user-images.githubusercontent.com/38659798/215039771-14f7cbf3-b820-4990-afda-a903a7c0f103.png)

**Comment by ssethupathy** [comment]
closed
