### ISSUE TITLE
Info endpoint

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#2058]
**A separate info endpoint** 
Should be used to collect data besides the existing copyright endpoint (#1685 license) for collecting:

- content title
- h5p library name and version 
- if a newer library version exists - then display this version in addition: "Latest version: Yes / version"
- publish status

It could, later on, be extended with more info:
- report current version status with time stamp and if a version with a newer timestamp

**Comment by ssethupathy** [comment]
closed

**Comment by emmachughes** [comment]
Reopening this as the necessary changes to edlibfacade have not been made yet.
