### ISSUE TITLE
Adjust MUI tabs text

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#2062]
The new mui component needs to have the new non-capital letters convention.

- [ ] H5P VEIW --> H5P view / H5P-visning (EN/NOB)

- [ ] SCRIPTVIEW --> Script view / Manusvisning (EN/NOB)

**Screenshot**
![Skjermbilde 2023-02-08 kl  15 01 03](https://user-images.githubusercontent.com/38659798/217565712-20394070-1f55-4e87-8baf-993e6327d98c.png)

**Comment by ssethupathy** [comment]
closed
