### ISSUE TITLE
Date picker date format in preview popup

### ISSUE THREAD

**Issue by chrieinv** [cerpus/Edlib#2071]
**Describe the bug**
On the preview form the date-pickers for the Views graph always have the same date format `m/d/y`, it should follow the language

**To Reproduce**

1. Go to 'Content Explorer' (aka www)
2. Click on a resource to open preview popup
3. The date-pickers for the graph always uses `m/d/y` date format

**Expected behavior**
It should use the date format for the language used

**Screenshots**
![image](https://user-images.githubusercontent.com/84850107/218676374-29f5f975-d727-4965-a19a-edb3c0ce7f60.png)

**Comment by ssethupathy** [comment]
This date format depends on the system settings (Region)
