### ISSUE TITLE
Edlib resource button icon is not displayed on HiDPI displays

### ISSUE THREAD

**Issue by emmachughes** [cerpus/Edlib#211]
**Describe the bug**
When editing an article, the icon for the Edlib resource button doesn't show up on HiDPI displays.

**To Reproduce**
1. Have a HiDPI display, or adjust the browser's zoom level to simulate one
2. Try editing a text resource

**Expected behavior**
The icon should be displayed.

**Screenshots**

<img width="559" alt="image" src="https://user-images.githubusercontent.com/84008144/143887137-41a25c34-06ec-4c29-a249-edd23d341e06.png">

<img width="286" alt="image" src="https://user-images.githubusercontent.com/84008144/143887205-db4702ad-2d21-425c-b591-7d65ec579d5f.png">

**Desktop:**

- OS: macOS 11.6
- Browser: Firefox
- Version: 94

**Additional context**

None.

**Comment by tmkarlsen** [comment]
Suggest removing the entry as this needs to be solved in context of the new article.

**Comment by tmkarlsen** [comment]
Duplicate: https://github.com/cerpus/Edlib/issues/74
