### ISSUE TITLE
Adjustment of font size

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#2170]
Adjusting the font size in several places should be tested to get a more consistent experience when navigating in content explorer.

**18 px Lato**
- Header entries - Create content, Shared content, and My content
- Left menu - top-level filtering
- Resource titles
- Note: Sub menu entries on Create content

**16 px Lato**
- Search 
- Left menu - second level filtering
- Left menu - Save filter + Grouped
- Left menu - Reset button
- Column headers

**14 px Lato**
- Content type on resource
- Date (on resource)
- Author (on resource)
- Language (on resource)
- Status (on resource)
- Views (on resource)
- Minimenu (three dots at the end of the resource)

**Comment by KashifIqbal1975** [comment]
New font sizes grouped with different colors to make it a bit easier to see.

![Content Explorer Lato 14px](https://user-images.githubusercontent.com/105861259/223384943-0d40a1ff-2170-4cec-adc8-981d62367ec5.png)
![Content Explorer Lato 16px](https://user-images.githubusercontent.com/105861259/223384956-61b2fdba-1bee-4f0b-b4eb-dd42828cd672.png)
![Content Explorer Lato 18px](https://user-images.githubusercontent.com/105861259/223384964-b9970437-97d2-47b1-8cb3-1cff40ed6f81.png)

**Comment by chrieinv** [comment]
@KashifIqbal1975 Need text-sizes for the grid-view. in the top right corner, click the button below the sort order drop down
