### ISSUE TITLE
Something happened error

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#2189]
Ran across a "Something happened" in CA as a resource that couldn't be edited in the NDLA-test environment.

![image (32)](https://user-images.githubusercontent.com/38659798/225608822-3a2f23a2-43c6-4a26-9eb4-3238108452c8.png)

We should have removed all these by now. We need to check for more of these and replace them with a more informing error message.

**Comment by ssethupathy** [comment]
closed
