### ISSUE TITLE
Missing components in Weblate

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#2190]
Look into if components are missing in Weblate that should be added.

Example:
https://github.com/cerpus/Edlib/tree/master/sourcecode/apis/contentauthor/resources/assets/react/language

**Comment by ssethupathy** [comment]
These translation files are not handled by weblate
`resources/assets/react/components/LinkContentType/language/en-gb.js
resources/assets/react/components/LinkContentType/language/nb-no.js
resources/assets/react/components/LinkContentType/language/nn-no.js
Edlib/sourcecode/apis/contentauthor/resources/assets/react/language/en-gb.js
Edlib/sourcecode/apis/contentauthor/resources/assets/react/language/nb-no.js
Edlib/sourcecode/apis/contentauthor/resources/assets/react/language/nn-no.js
Edlib/sourcecode/apis/contentauthor/resources/assets/react/language/sv-se.js`

**Comment by tmkarlsen** [comment]
@emmachughes, I'm assuming the LinkContentType files can be skipped?
