### ISSUE TITLE
Investigate: Missing file in h5p content types

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#2196]
A couple of files have gone missing in two custom NDLA H5P content types:

1. Missing icon files (thumbs-up +  trash can) in https://github.com/NDLANO/h5p-discussion

Files:

1. https://github.com/NDLANO/h5p-discussion/blob/master/assets/thumb.svg
2. https://github.com/NDLANO/h5p-discussion/blob/master/assets/trash.svg

Example:
https://www.h5p-test.ndla.no/s/resources/96d5fd34-26bb-4632-b0ba-e08634338ccb

3. Missing icon file (loading animation) in https://github.com/NDLANO/h5p-three-sixty

Example:
https://www.h5p-test.ndla.no/s/resources/34f41272-cdee-44cc-b365-28a3575c5236

Request URL: https://cdn.h5p-test.ndla.no/contentauthor/cachedassets/4a137b62206fd77bcd4d.svg

**Comment by otacke** [comment]
This is most likely an issue with how the content type build chain was modified and will need to be fixed in the H5P content type.

**Comment by tmkarlsen** [comment]
Thanks @otacke I think you are correct!

@janlindso did you try compiling and uploading these libraries again and did that work?

**Comment by otacke** [comment]
That issue probably petsists and needs slight changes. Will take a look.

**Comment by otacke** [comment]
@tmkarlsen @janlindso Should be fixed by https://github.com/NDLANO/h5p-discussion/pull/34/files

**Comment by tmkarlsen** [comment]
Nice, @otacke!
