### ISSUE TITLE
Double ExtraTitleField in H5P-image-silde

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#2201]
**Image Slider has one text field class too many**
Image Slider has two classes of "extratitle"

`<div class="field field-name-extraTitle text"><div class="h5p-editor-flex-wrapper"><label class="h5peditor-label-wrapper" for="field-extratitle-38"><span class="h5peditor-label h5peditor-required">Title</span></label><div role="button" tabindex="0" class="h5p-metadata-button-wrapper"><div class="h5p-metadata-button-tip"></div><div class="h5p-metadata-toggler">Metadata</div></div></div><div class="h5peditor-field-description" id="field-extratitle-38-description">Used for searching, reports and copyright information</div><input class="h5peditor-text" type="text" id="field-extratitle-38" aria-describedby="field-extratitle-38-description" value="Untitled Image Slide" maxlength="255"><div class="h5p-errors"></div></div>`

**Screenshots**
![Skjermbilde 2023-03-22 kl  08 21 14](https://user-images.githubusercontent.com/38659798/226829592-7bf23722-b2ff-47bb-b7f2-f5b6da52741d.png)

**Comment by chrieinv** [comment]
Not an issue with Edlib, the number of fields are according to the semantics for the H5P.ImageSlider.
The H5P.ImageSlider content types uses the H5P.ImageSlide content type that uses the H5P.Image content type, each get their own title field.
![image](https://user-images.githubusercontent.com/84850107/229720891-b9409795-a78e-45ac-9388-2bef17aee746.png)

**Comment by chrieinv** [comment]
It seems that the `library.json` file for H5P Image 1.1 contains a setting that should disable the extra title field, this setting seems to have no effect in Edlib.
