### ISSUE TITLE
No scipt view in H5P.ImageSlider

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#2203]
**Script view is empty for Image Slider**
Script view does not return any data for the fields, even though similar fields are shown for e.g. Course Presentation.

- Possible reason for the nynorsk-robot not working.
- Other issue reported for this content type regarding an extra titlefield #2201

**Comment by tmkarlsen** [comment]
Another content type with missing text field in Script View #2623

**Comment by chrieinv** [comment]
Image Slider uses the Image Slide library, that again uses the Image library.
Below is the part of the semantics for Image Slider that includes the Image Slide library. CA fails to get the fields for the used library if the library is the only item in a group. I.e. if the library was included in the list, or the group included a text input, the script-view would contain the input fields from the Image library.
```
{
    "label": "Images",
    "name": "imageSlides",
    "type": "list",
    "field": {
      "label": "Image Slide",
      "name": "imageSlide",
      "type": "group",
      "fields": [
        {
          "label": "Image Slide",
          "name": "imageSlide",
          "type": "library",
          "options": [
            "H5P.ImageSlide 1.1"
          ]
        }
      ]
    }
  },
```
