### ISSUE TITLE
Translations missing or not properly set up

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#2251]
**Translations missing when creating converting questionset to millionarie**
When trying to convert a questionset to a millionaire game, the error messages are not translated, but the translations _seems_ to be done in Weblate. They can be found as part of /php-game and /php-questions 

**Screenshot**

![Skjermbilde 2023-04-14 kl  08 36 06](https://user-images.githubusercontent.com/38659798/231965648-cc341948-4630-4baa-be40-999f84bc64ef.png)

![Skjermbilde 2023-04-14 kl  08 53 05](https://user-images.githubusercontent.com/38659798/231967117-4230b186-66f1-4daa-b294-93de9b31c6fc.png)

![Skjermbilde 2023-04-14 kl  08 54 23](https://user-images.githubusercontent.com/38659798/231967072-1a213037-a1d9-4a77-833e-5e4cc3e6ba81.png)

![Skjermbilde 2023-04-14 kl  08 53 56](https://user-images.githubusercontent.com/38659798/231967085-4f093bcd-79c6-444e-9d0d-9cc8fbb1ca2d.png)

**Comment by chrieinv** [comment]
@tmkarlsen Can you re-test this, should be fixed by PR #2521

**Comment by emmachughes** [comment]
Verified to be fixed.
