### ISSUE TITLE
Update language files for H5P libraries 

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#2589]
**In many cases, updating the language files in the H5P open-source project takes too long to return**
The problem is that these small language fixes are easily done and should be quick to update, but it takes time for the whole circle to complete.

__Suggested solutions__

1. ~~Being able to upload and actively overwrite an existing/installed H5P library~~
2. ~~Being able to upload and overwrite language files for installed H5P libraries~~
3. Update the copy of the language files that are stored in the database

__Described solution__
Description of accepted solution 3
1. Translations made in [Weblate](https://translate-h5p.tk/weblate/projects/h5p/) are downloadable and can be uploaded as a JSON file in CA-admin. The save process will consist of a validation before the database is updated.
2. Admins can also edit translations directly within a text field in CA-admin. The save process will consist of a validation before the database is updated.

**Comment by chrieinv** [comment]
When a library is installed, the content of the translation files are stored in the database. When H5P Editor requests a translation it is retrieved from the database.
In the Admin interface it will be possible to edit the translations stored in the database, the translations are stored as a JSON string. The translations will be local, meaning that they will not be included when exporting. Changes to the translations stored in the database may be overwritten when a new patch-version of a library is installed.
