### ISSUE TITLE
Main textfield in H5P Vocabulary Drill does not display in Script View

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#2623]
**The task text field is missing in Script View for Vocabulary Drill**

https://github.com/NDLANO/h5p-vocabulary-drill

The "word field" does not display in Script view

**Test resoruce**
https://www.h5p-test.ndla.no/s/resources/a3d5a00d-fbd3-4bfc-8141-e3f250b99bc5

**Comment by chrieinv** [comment]
The fields that is listed are of type `text`. Widget must be undefined or one of the following:
- textarea
- html
- showWhen
- NDLAShowWhen
