### ISSUE TITLE
Bulk update for course presentation fails

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#2653]
**Bulk update fails for drag and drop**

When trying to bulk update H5P.CoursePresentation 1.7.0 (to 1.8.2), nothing seems to happen and the error message below is displayed in the console

**Error message in console:**
h5p-content-upgrade.js?ver=2.0.3:438 Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at ContentUpgrade.printError (h5p-content-upgrade.js?ver=2.0.3:438:91)
    at Worker.error (h5p-content-upgrade.js?ver=2.0.3:124:14)
    at self.workers.<computed>.onmessage (h5p-content-upgrade.js?ver=2.0.3:147:46)

**Screenshots**
![Skjermbilde 2024-01-04 kl  12 41 51](https://github.com/cerpus/Edlib/assets/38659798/7e48e0c9-5cf3-41e8-979a-fa938f870b9f)

**Comment by chrieinv** [comment]
Here we have two issues.
- The first is a missing error message, this causes the upgrade process to crash, it should just print the error message and continue
- The second is the issue causing the error, this is something in the content. If the error message wasn't missing it would read `Parameters contain ? which is not supported.`, where ? is a content library
