### ISSUE TITLE
500 on H5P.ImageSlide content version 1.1.7

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#2658]
**NDLA_test**
Several H5P.Imageslider results in 500 (fronend and edit). 
This could be due to the bulk update 09.01.2024.

**500-error resource (examples):** 
https://www.h5p-test.ndla.no/s/resources/48ff0f52-2bb8-4c34-abb3-3b5972c9abca
https://www.h5p-test.ndla.no/s/resources/7045ccd6-5f14-46a3-ac6b-c83410b5b8f9

**Unable to find constructor for: H5P.ImageSlide 1.1 + Uncaught TypeError**
Nyhetsbilder fra 1900 til og med 1950-tallet
https://www.h5p-test.ndla.no/s/resources/322fbf48-82ea-4e8f-8c78-dd85a9288213

**Screenshot**
![Skjermbilde 2024-01-16 kl  10 06 15](https://github.com/cerpus/Edlib/assets/38659798/75b198bf-62bd-4334-9187-b2d03189149e)

**Comment by chrieinv** [comment]
The library H5P.ImageSlide 1.1 is not installed

**Comment by tmkarlsen** [comment]
https://github.com/falcon-git/h5p-image-slide
