### ISSUE TITLE
Add decoding for missing HTML in Script View fields without CKEditor

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#2662]
The following characters entities must be supported by Script View in coding/decoding.
  
 < 
 > 
 ' 
 "
 
 **Screenshots of examples**
![2022-11-28 10 49 56 ed ndla no fe912cb359b0](https://github.com/cerpus/Edlib/assets/38659798/91d53f83-02af-4597-ae56-436f7be5347e)

![image (37)](https://github.com/cerpus/Edlib/assets/38659798/3fe1f19b-7de3-4425-9eb7-e59666cb0f91)

**Comment by chrieinv** [comment]
Encoding characters `' " < >`
