### ISSUE TITLE
Preview modal size

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#2681]
The preview modal's size should be determined by the size of the screen, and the size of the iframe Edlib is loaded within. 

Use bootstrap settings for fullscreen modal: .modal-fullscreen-md-down | 768px to ensure a full screen on preview modal when opening Edlib in a small iframe/modal

https://getbootstrap.com/docs/5.3/components/modal/#optional-sizes

**Screenshot**
<img width="1733" alt="Skjermbilde 2024-02-19 kl  11 06 56" src="https://github.com/cerpus/Edlib/assets/38659798/e2d4b4c9-0167-40e8-b7c2-6138c9a7e12f">

**Comment by emmachughes** [comment]
Fixed in [2d9bde1](https://github.com/cerpus/Edlib3/commit/2d9bde10c6baeb4bea0a54b0d2220bbdd7024eed)
