### ISSUE TITLE
502: Make sure user is sent to login screen if session expires

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#2703]
**502 error**
The user is often logged out and met with a not-so-informative message.

**Screenshot**
![Skjermbilde 2024-03-22 kl  13 40 02](https://github.com/cerpus/Edlib/assets/38659798/711ce74b-4bc2-4f27-a55f-3aa9840f5077)

**Comment by emmachughes** [comment]
Likely Vapor-related.

**Comment by tmkarlsen** [comment]
Re-tested leaving Edlib open at content/mine and came back to the login screen after a couple of days ✅
