### ISSUE TITLE
Update H5P core and editor

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#2733]
Several H5P libraries require version 1.26 of coreApi, and an update needs to be assessed. 

- [ ] Update H5P core
- [ ] Update H5P editor 

Udpate "h5p-core" from current commit 0a82667 to latest commit f5d27a5
https://github.com/h5p/h5p-php-library/commits/master/

Update h5p-editor from current commit 0365b08 to latest commit b820227
https://github.com/h5p/h5p-editor-php-library/commits/master/

**Comment by chrieinv** [comment]
H5P Core is updated to f3579c0d28205bf34490ee151c07d43a2ffc3507, taking the core API to version 1.26
H5P Editor is updated to e442a251a6eda93043c637f5bf19beb60e92191b
