### ISSUE TITLE
CA Game Millionaire is trying to load a CSS file that is no longer built

### ISSUE THREAD

**Issue by chrieinv** [cerpus/Edlib#2741]
The Millionaire Game tries to load `css/game.css`, this file was removed in https://github.com/cerpus/Edlib3/commit/91b46def05fa462d02f922c31ab3f3ffd04f5fe4

**Comment by emmachughes** [comment]
Fixed in https://github.com/cerpus/Edlib3/commit/d2b31de31dc4304f0d416f2bd7cf5686fbc356a8
