### ISSUE TITLE
Cards: Maintain padding and placement of buttons

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#2781]
Make sure padding on buttons are kept on cards with various data

- [ ] The edit and use buttons must not be pushed or lose padding when the author takes two lines as a maximum (it will truncate after 70 letters #2762 )

![Image](https://github.com/user-attachments/assets/f564707a-bc19-43e0-b691-b7568ef042b0)

**Comment by chrieinv** [comment]
Instead of cutting at 70 characters, it is cut at two lines adding `…` at the end
