### ISSUE TITLE
Endpoint for license returns 500

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#38]
**Describe the bug**
The endpoint for retrieving license from H5Ps used within an article is returning 500 ndla.no.

	
`curl -X GET "https://h5p-staging.ndla.no/v1/resource/fa9a0177-56db-4990-9506-5560c35c743f/copyright" -H "accept: /"`

**To Reproduce**
1. Open https://ndla.no/subject:d1fe9d0a-a54d-49db-a4c2-fd5463a7c9e7/topic:077a5e01-6bb8-4c0b-b1d4-94b683d91803/topic:56ec5eb2-a27d-4707-8fa2-f5ef7d3cc164/topic:d231ffca-5b19-4c7f-9f92-f922f800bcb7/resource:6840dc4a-bff2-4174-9544-c892ec5f53ba
2. Scroll down to "Regler for bruk"
3. The dialogue should have an separate H5P tab displaying the used H5Ps and their license like the attached image.  
![Skjermbilde 2021-09-24 kl  13 44 59](https://user-images.githubusercontent.com/38659798/134677840-f4f3b287-9a65-4684-9ab5-05b995a459c3.png)

Link to working resource in prod: https://ndla.no/subject:1:605d33e0-1695-4540-9255-fc5e612e996f/topic:1:da32242e-8fe8-4a4b-9e02-f9e61fa122ef/topic:1:6bc59798-daab-4799-8159-c3ccb24cf6e8/resource:6a5fe992-a507-44b4-b516-66ab2c8c2c2a

**Comment by maxmoeschinger** [comment]
Create a pull request here: https://stash.cerpus.com/projects/BRAIN/repos/edlibfacade/pull-requests/46/overview
I have also update the configuration for facadeapi in all environments for NDLA to have the content author url.

**Comment by maxmoeschinger** [comment]
@tmkarlsen The code is now on test. Can you test that everything is working as expected?

**Comment by tmkarlsen** [comment]
Tests shows that this is now working correctly.
