### ISSUE TITLE
Add Korean translation

### ISSUE THREAD

**Issue by brettkromkampcerpus** [cerpus/Edlib#451]
Add Korean translation to Edlib. The necessary translation files have been provided as part of this issue.

[ko-gb.zip](https://github.com/cerpus/Edlib/files/7860948/ko-gb.zip)

**Comment by brettkromkamp** [comment]
Contributed by:
Jeonghun Oh - Busan Institute for Future Education (BIFE)
jeonghunoh@korea.kr

**Comment by totoromaum** [comment]
Thank you, Brett. Have a great one!
