### ISSUE TITLE
Investigate bug in the H5P update script

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#455]
**Describe the bug**
When updating library versions on H5P-resources, some libraries experience both or one of the following errors:

1. The H5P title is overwritten with data from the next input field (E.g. Documentation Tool)
2. The data within H5P "Metadata" is dropped

**Affected libraries**
These are the ones documented so far:
- Single Choice: error 1 (title is overwritten)
- Dialog Cards: error 1 and 2 (title is overwritten + metadata is emptied)
- Documentation Tool: error 1 and 2 (title is overwritten + metadata is emptied)
- Find the hotspot: error 1 (title is overwritten)
- True/false: error 1 (title is overwritten)
- Column: error 1 (title is overwritten) 

**To Reproduce**

1. Find an old Documentation tool within "Shared content"'
2. Edit, verify and document the attribution data in the H5P "Metadata" and the title of the resource
3. Choose the latest upgrade version and upgrade (Note: do not save and close after the upgrade has run) 
4. Verify that the title has been changed and the metadata dropped.

**Expected behavior**
Title and metadata (like anything else) should not be affected by version upgrades of H5P-resources 

**Screenshots**

Note: the update of this Documentation Tool was done from a 1.6.x version to  1.8.9

<img width="1745" alt="Skjermbilde 2022-01-13 kl  10 38 04" src="https://user-images.githubusercontent.com/38659798/149306744-a25325c7-5ca6-4057-82f0-4ba331fa4dd7.png">
<img width="1746" alt="Skjermbilde 2022-01-13 kl  10 38 30" src="https://user-images.githubusercontent.com/38659798/149306788-0dcf42c1-1eb5-4ff5-ae88-469bea48f65b.png">
<img width="1745" alt="Skjermbilde 2022-01-13 kl  10 37 53" src="https://user-images.githubusercontent.com/38659798/149306827-f31bd8e4-e887-46be-b36e-dc20cd728df1.png">
<img width="1746" alt="Skjermbilde 2022-01-13 kl  10 37 42" src="https://user-images.githubusercontent.com/38659798/149306859-70b5cef3-8c5e-496a-b09e-cc92de08e980.png">

**Comment by tmkarlsen** [comment]
Doc.tool:
https://github.com/h5p/h5p-documentation-tool/blob/master/upgrades.js
Seemes like the updating of title from the upgrade.js clears out all existing data in the metadata section.
We need to verify if this is because of the way we add the author or not.

True/false:
https://github.com/h5p/h5p-true-false/blob/master/upgrades.js

**Comment by maxmoeschinger** [comment]
@tmkarlsen er dette noe som Joubel jobber med?

**Comment by tmkarlsen** [comment]
@maxmoeschinger we have created an issue on one of their repos' regarding this, yes.
https://github.com/h5p/h5p-documentation-tool/issues/47
