### ISSUE TITLE
'Unprocessable content' error from API endpoint 'context-resource-collaborators'

### ISSUE THREAD

**Issue by chrieinv** [cerpus/Edlib#460]
**Describe the bug**
POST from Edstep to the 'context-resource-collaborators' API endpoint results in a 422 with message
`{"message":"The given data was invalid.","errors":{"context":["The context field is required."]}`
The context field is set in the data sent from Edstep

**To Reproduce**
In Edstep publish a course containing an Edlib resource

**Expected behavior**
No error

**Comment by emmachughes** [comment]
Configuration issue unrelated to Edlib.
