### ISSUE TITLE
JS error in embed from resource

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#471]
**Describe the bug**
There is a JS bug that _could_ be preventing the resize.script to work properly when embedding a resource from h5p.ndla.no

**To Reproduce**
Embed a resource into the source code of any page. Example:
<iframe src="https://www.h5p.ndla.no/s/resources/e725cbec-2997-4fd9-bc2c-a52590c14f79" width="771" height="459"></iframe><script src="https://h5p.org/sites/all/modules/h5p/library/js/h5p-resizer.js"></script>

 
**Error message**
TypeError: Cannot read properties of null (reading 'type')
    at 2.fc6543ff.chunk.js:2:3394417
    at s (2.fc6543ff.chunk.js:2:2842232)
    at Generator._invoke (2.fc6543ff.chunk.js:2:2842020)
    at Generator.next (2.fc6543ff.chunk.js:2:2842657)
    at n (2.fc6543ff.chunk.js:2:2602889)
    at i (2.fc6543ff.chunk.js:2:2603100)
(anonymous) @ 2.fc6543ff.chunk.js:2
Promise.catch (async)
(anonymous) @ 2.fc6543ff.chunk.js:2
(anonymous) @ 2.fc6543ff.chunk.js:2
(anonymous) @ 2.fc6543ff.chunk.js:2
setInterval (async)
(anonymous) @ 2.fc6543ff.chunk.js:2
Rl @ 2.fc6543ff.chunk.js:2
t.unstable_runWithPriority @ 2.fc6543ff.chunk.js:2
Wa @ 2.fc6543ff.chunk.js:2
xl @ 2.fc6543ff.chunk.js:2
(anonymous) @ 2.fc6543ff.chunk.js:2
F @ 2.fc6543ff.chunk.js:2
M.port1.onmessage @ 2.fc6543ff.chunk.js:2

**Comment by chrieinv** [comment]
@tmkarlsen Please retest, unable to reproduce error

**Comment by tmkarlsen** [comment]
@chrieinv Me neither. Closing issue.
