### ISSUE TITLE
Many different versions of Node in use

### ISSUE THREAD

**Issue by chrieinv** [cerpus/Edlib#593]
**Is your feature request related to a problem? Please describe.**

When building the project five different images of Node is downloaded

| Node version | Uses | Size |
| ---------------| ----- | ----- |
| 14.18 | 1 | 944MB |
| 14 | 4 | 946MB |
| 16.13 | 1 | 905MB |
| 16 | 6 | 906MB |
| 16-alpine | 6 | 109MB |

**Describe the solution you'd like**
Fewer Node versions used, preferable only one

**Comment by emmachughes** [comment]
It seems the obvious solution would be to switch to Alpine-derived images. I'm not aware of any reason we should be sticking with the Debian-based images.

**Comment by maxmoeschinger** [comment]
I don't think there is any reason. We should use 16.13-alpine on all repos

**Comment by chrieinv** [comment]
The scripts in `localSetup/helpers/start-scripts` are not executed when using 16-alpine, the logs says `not found`

**Comment by chrieinv** [comment]
**Update:** All projects are updated to use node 16-alpine, except one. The `Docs` project is on node 14

**Comment by tmkarlsen** [comment]
@chrieinv can you update the remaining `Docs` project?
