### ISSUE TITLE
GDPR user and content delete/anonymisation

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#64]
**Delete all user related content within Edlib**
When an application performs a user and content delete, the affiliated Edlib data should be anonymized. 
 
**Solution**
To be described

**Comment by maxmoeschinger** [comment]
The conclusion is that we do not remove anything but anonymize all user information for a given user id provided by the external service.

- **First name:** GDPR Anon
- **Last name:** <Deletion request id>
- **Email:** gdpr-anon-<deletion request id>@edlib.com

**Comment by maxmoeschinger** [comment]
Release in version [1.7.0](https://github.com/cerpus/Edlib/releases/tag/1.7.0)
