### ISSUE TITLE
H5P libraries missing translations in CA?

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#652]
**Lack of translations**
CA seem to be missing a lot of available translations for H5P. Are there custom translations made that could be blocking the ones from the H5P-libraries?

**Comment by tmkarlsen** [comment]
Estimate: 1 week.

**Comment by tmkarlsen** [comment]
This issue should be retested when #23 is out.

**Comment by tmkarlsen** [comment]
When NDLA Facade has been updated on test/prod, this can be tested on their environments.

**Comment by tmkarlsen** [comment]
@Kamelon7 this issue seems to be fixed. If no other CA components are missing in Weblate, this issue can be closed I guess.

**Comment by Kamelon7** [comment]
Yes, the missing components have been added (details can be found in the [Jira case](https://cerpus.atlassian.net/browse/HOS-143). It's not perfect, due to how the translation project was initially set up, but it's functional.
