### ISSUE TITLE
Missing icons for image editing

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#747]
**Icons and view for image editing must be fixed **
The icons and view for editing images within H5P must be fixed.

**Screenshot**
![Skjermbilde 2022-02-28 kl  09 40 10](https://user-images.githubusercontent.com/38659798/156373108-cd0d626d-346d-4d8d-a46b-3bd85c4448b3.png)

vs

![Skjermbilde 2022-03-02 kl  14 39 32](https://user-images.githubusercontent.com/38659798/156373246-e3ae4704-0495-44f0-ae6e-385ab43d56bd.png)

**Comment by tmkarlsen** [comment]
Is is unclear what's causing this. Estimate is therefore 2 days.

**Comment by chrieinv** [comment]
The reason is that NDLA loads some custom scripts, one of these is the `h5peditor-image-pop.js` that loads the image editor. This uses a custom style that is not loaded in the editor iframe
