### ISSUE TITLE
"Responsive view" - language filter missing

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#748]
**When downsizing Edlib - language search goes away **
Language search dropdown should not be dropped.

**Screenshot**
![Skjermbilde 2022-03-02 kl  15 17 17](https://user-images.githubusercontent.com/38659798/156379411-3090faba-9ab9-4c2b-998f-36133df23598.png)

**Comment by maxmoeschinger** [comment]
On test

**Comment by chrieinv** [comment]
@tmkarlsen Please retest, should be fixed in #1652
