### ISSUE TITLE
Switch to card view for tablet and smaller.

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#749]
**Responsiveness**
Make sure the different columns is not stacked above each other. 

1. Switch over to card view for tablet/break point.
2. Look over break points and make sure it updates in time.

**Screenshot**
![Skjermbilde 2022-03-02 kl  15 22 28](https://user-images.githubusercontent.com/38659798/156379917-c2207c0f-408c-4328-979b-fd2513352adf.png)

**Comment by maxmoeschinger** [comment]
@tmkarlsen On test
