### ISSUE TITLE
Paste and replace does not work on existing resources

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#757]
**Paste and replace does not work**
Paste and replace does not work **on existing resources**. If you do in the H5P Hub, the new resource is created and the old content pasted, but on existing resources nothing seem to happen and CA does not time out.

**Comment by chrieinv** [comment]
This is a bug in Composer package `h5p/h5p-editor`, it's fixed but not released. Current latest release is 1.24.4
The commit that fixes the issue: https://github.com/h5p/h5p-editor-php-library/commit/f712ee5963c2904eba6c993bc8c430c327f0d07f
