### ISSUE TITLE
Investigate: fullscreen view for new NDLA-specific content type

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#772]
NDLA Interactive Tavle enables new aspects (portrait) and need to make use of the height in stead of the width when calculating size for fullscreen view.

WP seems to handle this differently than Edlib and we need investigate why.
WP: https://nettstudiene.no/tmk-test-2
Ed/edlib-test: https://ed.test.ndla.no/subject-matter/learning-resource/31229/edit/nb / https://ed.test.ndla.no/preview/31229/nb

**Screenshots**
Ed/Edlib-test normal "article-view"
![Skjermbilde 2022-03-09 kl  12 14 31](https://user-images.githubusercontent.com/38659798/157431006-eb4f3efa-b3e6-477d-9708-d0eb824e202f.png)
Ed/Edlib-test fullscreen veiw. Image below shows full with use of H5P without possibility to scroll:
![Skjermbilde 2022-03-09 kl  12 14 38](https://user-images.githubusercontent.com/38659798/157431047-c3b8dd63-5f8b-48ba-833b-d4ae0a4bb4ad.png)
Nettstudiene (WP) fullscreen veiw
![Skjermbilde 2022-03-09 kl  12 25 44](https://user-images.githubusercontent.com/38659798/157432640-639e8de2-2b41-465b-9eaf-ab58cff1575b.png)

**Comment by chrieinv** [comment]
Seems to be an issue with the H5P. The HTML-element that is set as fullscreen is also resized, this does not work. The element that is resized must be a child element of the fullscreen element.

**Comment by chrieinv** [comment]
A different way of fixing this issue could be done by adjusting the CSS.
On the element with `class="h5p-wrapper"`, replace the calculated `padding-top` with `width` and `height` calculation, and on the `.h5p-box-wrapper` CSS class, remove `position: absolute;`. The subtracted values in the formulas below are headers, footers etc., and can be fine-tuned, but the values below should give roughly the same size as current.

For a ratio where it should use as much height as possible, the formulas are:
```
   height: calc(100vh - 1.41em - 0.75em);
   width: calc((100vh - 1.41em - 0.75em - 2.2em) * <ratio>);
```
and for ratios where it should use as much width as possible:
```
   height: calc((100vw - 1.41em - 0.75em) / <ratio>);
   width: calc(100vw - 1.41em - 0.75em - 2.2em);
```

So for a 3/4 ratio, i.e. height, the result will be:
```css
   height: calc(100vh - 1.41em - 0.75em);
   width: calc((100vh - 1.41em - 0.75em - 2.2em) * (3 / 4));
```

and for a 4/3 ratio, i.e. width:

```css
   height: calc((100vw - 1.41em - 0.75em) / (4 / 3));
   width: calc(100vw - 1.41em - 0.75em - 2.2em);
```
