### ISSUE TITLE
Editor goes through erratic size changes in certain browser sizes

### ISSUE THREAD

**Issue by Kamelon7** [cerpus/Edlib#781]
**Describe the bug**
When browser window is approx 1700 x 1300 px in size, the editor will change size rapidly. Found while making an interactive video.

**To Reproduce**

1. Create a new interactive video
2. Insert Youtube video
3. Go to "Add interactions"
4. Make sure browser window is approx. 1700 x 1300
5. Editor window starts to move erratically

![chrome-capture (2)](https://user-images.githubusercontent.com/82902462/157841506-e83bd304-d820-4b44-aef6-5f5b439e5e40.gif)
Movement is more rapid than the gif can capture

- OS: Windows 11
- Browser: Firefox, Edge
- Version: Latest available

**Comment by Kamelon7** [comment]
Tested with more sizes, horizontal size needs to be >1300px

**Comment by chrieinv** [comment]
The issue occurs on certain screen sizes and usually with H5P content types that uses canvas in the editor (like 'Course Presentation' and 'Interactive Video'.
The height of the editor causes the scrollbar to be displayed, this triggers a reduction of the with, and to keep the aspect ratio of the canvas the height is reduced. The height reduction is enough that the scrollbar is no longer needed, and the browser removes it. The width and height of the canvas then increases and the scrollbar is again required. This creates a never ending loop of displaying/hiding the scrollbar and resizing of the canvas.
