### ISSUE TITLE
Go over translations for licenses on weblate

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#790]
Verify that the translations are correct according to the translations made on https://creativecommons.org/publicdomain/mark/1.0/deed.no

https://weblate.edlib.com/translate/www/www/nb_NO/?q=has:comment

Example from NDLAs translations
![Skjermbilde 2022-03-14 kl  13 39 21](https://user-images.githubusercontent.com/38659798/158174850-9eab36b3-4cae-42da-a4c7-dac3f99abe35.png)

**Comment by Kamelon7** [comment]
The Norwegian translation of CC licenses has already been corrected according to CC's [own translations](https://creativecommons.org/about/cclicenses).
I've also added spacing to avoid the spacing issues seen in the screenshot above.
