### ISSUE TITLE
Double vertical scrollbar when selecting content type to create

### ISSUE THREAD

**Issue by chrieinv** [cerpus/Edlib#880]
**Describe the bug**
When selecting which interactive content type to create a double vertical scrollbar is displayed

**To Reproduce**

1. Select "Create content" and "Interactivity"
2. A double vertical scrollbar is displayed, one for the tab content and one for the content types list

**Expected behavior**
Only one vertical scrollbar

**Screenshots**
![image](https://user-images.githubusercontent.com/84850107/159243906-90db0181-ef30-49e8-bd59-1a7a7940e94e.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Firefox
- Version: 98.0.1

**Additional context**
Edlib was opened from Edstep on Test environment. Same issue in local dev environment using Storybook

**Comment by tmkarlsen** [comment]
The double scrollbar appears in all parts of Edlib

**Comment by chrieinv** [comment]
Looks like it's caused by code that's part of the `h5p/h5p-editor` Composer package, the list of H5Ps is using a fixed height
