### ISSUE TITLE
Improve norwegian "Rights of use" translation of Author for H5P

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#92]
The translation of "Author" should be updated from "Opphavsmann" as it is not gender specific to:
nob: "Opphaver"
nno: "Opphavar" 

This information is found within the "Rights of use" in the H5P footer.
![Skjermbilde 2021-10-29 kl  11 30 12](https://user-images.githubusercontent.com/38659798/139411887-5c2fc272-c7c4-456e-b101-b8f008fa3c51.png)

**Comment by Kamelon7** [comment]
Changed in [Weblate](https://weblate.edlib.com/translate/content-author/php-h5p-editor/nb_NO/?checksum=cbd169a73682c197&sort_by=-priority,position). Nno translation also added.
