### ISSUE TITLE
Choosing video player from Brightcove

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#933]
When enabling the new player for 360 degree videos, this seem to be the player chosen for all cases. 
This COULD cause difference in behavior rendering of videos.

360 Brightcove video player: id = oB5bDFv99
Ordinary Brightcove video player id = BkLm8fT

https://ca.h5p-test.ndla.no/js/videos/brightcove.js

API reference: https://apis.support.brightcove.com/cms/references/cms-api-video-fields-reference.html
The property `projection` is "_The mapping projection for 360° videos_", so a value other than `null` would indicate a 360 video

**Comment by tmkarlsen** [comment]
Estimate 3 days.

**Comment by chrieinv** [comment]
@tmkarlsen What content types are these?

**Comment by tmkarlsen** [comment]
This has to do with the general NDLA video integration in H5P, and has no specific content type. 
It is supported by e.g. Course Presentation and Interactive video

**Comment by tmkarlsen** [comment]
URL in video is used to determine player ID.
https://bc/0/12345678 => Path is 0, will use normal player  --> Player ID: BkLm8fT
https://bc/360/12345678 => Path is 360, will use 360 player --> Player ID: oB5bDFv99

**Comment by chrieinv** [comment]
If path is missing, e.g. for video inserted before this change, the 360 player will be used
