### ISSUE TITLE
NDLA frontend libraries leak global CSS that affect Content Author

### ISSUE THREAD

**Issue by emmachughes** [cerpus/Edlib#943]
Over the years, Content Author had various customisations for NDLA that are present in "NDLA mode" added to it. These are largely undocumented, and sometimes buggy as shown here: 

![image](https://user-images.githubusercontent.com/84008144/161019679-7ca178de-60b4-4294-8909-6f6fdb7b6ff4.png)

We should identify these customisations, remove the ones no longer needed, document the remaining ones, and keep them largely contained to a few locations instead of leaving them sprinkled across the codebase.

See also #942

**Comment by tmkarlsen** [comment]
Estimate 1-2 weeks.

**Comment by emmachughes** [comment]
The increased size of the sidebar goes away when `react-contentbrowser.js` is removed from the `NDLAH5PAdapter::getConfigJs`. Seemingly, it is CSS from the `@ndla/*` libraries that causes it.
