### ISSUE TITLE
Enable exact search

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#98]
**Enhancing search within Content Explorer gives a better experience**
Enabling exact search using "" will give a tool for the users searching and finding for that special resource.

**Possible solution**
By using "" to get an exact search user will get a better understanding of how it works. 
Note: we should look into how the partial search of today works and see what adjustments that can be made to make it mor understandable.

**How to recreate**
Searching for _redskap_ gives hits on partials ending with _-skap_  such as  _Skriftlig budskap_ and _Budsjett og regnskap_ see examples below:

![Skjermbilde 2022-08-22 kl  15 40 44](https://user-images.githubusercontent.com/38659798/185935462-e149a44f-828e-4e53-a65a-a5cab59b5098.png)

**Comment by tmkarlsen** [comment]
Estimate 34,8 hours (PERT)

**Comment by emmachughes** [comment]
The Edlib 3 hub has this. Exact phrases can be enclosed in double quotes.
