### ISSUE TITLE
503 on inserted H5Ps within articles

### ISSUE THREAD

**Issue by tmkarlsen** [cerpus/Edlib#99]
**H5Ps in articles does probably have the wrong URL **
All H5Ps in articles display 503.

**To Reproduce**
Find a course with an article with a H5P within. Search for "Celler og vekst"
![Skjermbilde 2021-11-04 kl  13 03 14](https://user-images.githubusercontent.com/38659798/140310280-cd3898ba-e7a0-4526-a32d-b486b269e31b.png)

**Comment by maxmoeschinger** [comment]
Fixed in https://github.com/cerpus/Edlib/releases/tag/1.5.6
